export const TEXT = Object.freeze({
  TITLE: "Visualizador Organigrama",
  SUBTITLE:
    "Importa un archivo CSV o Excel para visualizar el organigrama de tu empresa",
  REMOVE_FILTER: "Quitar filtro",
  FILTER_BY_MONTH: "Filtrar por Mes",
  NO_DATA: "No hay datos para mostrar",
  IMPORT_DATA: "Importar datos",
  SEE_CHART: "Ver Organigrama",
  SEE_TABLE: "Ver Tabla",
  MONTH: "Mes",
  NAME: "Nombre",
  ID: "ID",
  NO: "No",
  REAL_ID: "id",
  INCOME_DATE: "Fecha de ingreso",
  GROSS_SALARY: "Sueldo bruto",
  DIVISION: "División",
  AREA: "Área",
  SUBAREA: "Subarea",
  LEADER_ID: "ID Lider",
  HIERARCHICAL_LEVEL: "Nivel Jerárquico",
  ACCEPTED_FORMATS: "Formatos aceptados: .csv, .xlsx, .xls",
  ORGANIZATION_CHART: "Organigrama",
  UPLOAD_IMAGE: "Haz click para subir la imagen",
  TOTAL: "Total Nómina",
  PROMOTED: "Promovidos",
  NEW_HIRES: "Nuevos Ingresos",
  NO_PROMOTED: "No hay promovidos",
  NO_NEW_HIRES: "No hay nuevos ingresos",
});
