export const TEXT = Object.freeze({
  es: {
    TITLE: "Visualizador Organigrama",
    SUBTITLE:
      "Importa un archivo CSV o Excel para visualizar el organigrama de tu empresa",
    REMOVE_FILTER: "Quitar filtro",
    FILTER_BY_MONTH: "Filtrar por Mes",
    NO_DATA: "No hay datos para mostrar",
    IMPORT_DATA: "Importar datos",
    SEE_CHART: "Ver Organigrama",
    SEE_TABLE: "Ver Tabla",
    MONTH: "Mes",
    MONTH_LABEL: "Mes",
    NAME: "Nombre",
    NAME_LABEL: "Nombre",
    ID: "ID",
    NO: "No",
    REAL_ID: "id",
    INCOME_DATE: "Fecha_de_ingreso",
    INCOME_DATE_LABEL: "Fecha de ingreso",
    GROSS_SALARY: "Sueldo_bruto",
    GROSS_SALARY_LABEL: "Sueldo bruto",
    DIVISION: "Division",
    DIVISION_LABEL: "División",
    AREA: "Area",
    AREA_LABEL: "Área",
    SUBAREA: "Subarea",
    LEADER_ID: "ID_Lider",
    LEADER_ID_LABEL: "ID Lider",
    HIERARCHICAL_LEVEL: "Nivel_Jerarquico",
    HIERARCHICAL_LEVEL_LABEL: "Nivel Jerárquico",
    ACCEPTED_FORMATS: "Formatos aceptados: .csv, .xlsx, .xls",
    ORGANIZATION_CHART: "Organigrama",
    UPLOAD_IMAGE: "Haz click para subir la imagen",
    TOTAL: "Total Nómina",
    PROMOTED: "Promovidos",
    HIRES: "Nuevos Ingresos",
    NO_PROMOTED: "No hay promovidos",
    NO_NEW_HIRES: "No hay nuevos ingresos",
    PRINT: "Imprimir Organigrama",
    CHANGE_LANGUAGE: "Cambiar idioma",
  },
  en: {
    TITLE: "Organizational Chart Viewer",
    SUBTITLE:
      "Import a CSV or Excel file to visualize your company's organizational chart",
    REMOVE_FILTER: "Remove filter",
    FILTER_BY_MONTH: "Filter by month",
    NO_DATA: "No data to display",
    IMPORT_DATA: "Import data",
    SEE_CHART: "View Organizational Chart",
    SEE_TABLE: "View Table",
    MONTH: "Mes",
    MONTH_LABEL: "Month",
    NAME: "Nombre",
    NAME_LABEL: "Name",
    ID: "ID",
    NO: "No",
    REAL_ID: "id",
    INCOME_DATE: "Fecha_de_ingreso",
    INCOME_DATE_LABEL: "Income date",
    GROSS_SALARY: "Sueldo_bruto",
    GROSS_SALARY_LABEL: "Gross salary",
    DIVISION: "Division",
    DIVISION_LABEL: "Division",
    AREA: "Area",
    AREA_LABEL: "Area",
    SUBAREA: "Subarea",
    LEADER_ID: "ID_Lider",
    LEADER_ID_LABEL: "Leader ID",
    HIERARCHICAL_LEVEL: "Nivel_Jerarquico",
    HIERARCHICAL_LEVEL_LABEL: "Hierarchical level",
    ACCEPTED_FORMATS: "Accepted formats: .csv, .xlsx, .xls",
    ORGANIZATION_CHART: "Organizational Chart",
    UPLOAD_IMAGE: "Click to upload image",
    TOTAL: "Total Payroll",
    PROMOTED: "Promotions",
    HIRES: "New Hires",
    NO_PROMOTED: "No promotions",
    NO_NEW_HIRES: "No new hires",
    PRINT: "Print Organizational Chart",
    CHANGE_LANGUAGE: "Change language",
  },
});

export const NUMBERS = Object.freeze({
  NO: 50,
  MONTH: 80,
  NAME: 130,
  ID: 120,
  INCOME_DATE: 130,
  GROSS_SALARY: 100,
  DIVISION: 110,
  AREA: 90,
  SUBAREA: 90,
  LEADER_ID: 110,
  HIERARCHICAL_LEVEL: 130,
  PAGINATION: 10,
  PAGINATION_OPTIONS: [10, 20, 50],
});
